[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DAQUA_APP_RULES_V1

lib_deps =
  adafruit/Adafruit SHT31 Library
  adafruit/Adafruit INA219
  milesburton/DallasTemperature
  paulstoffregen/OneWire
  madhephaestus/ESP32Servo
  adafruit/DHT sensor library

[env:test_sensor_1]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DAQUA_APP_TEST_SENSOR_1
lib_deps =
  adafruit/Adafruit SHT31 Library

[env:test_sensor_2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DAQUA_APP_TEST_SENSOR_2
lib_deps =
  adafruit/Adafruit SHT31 Library

[env:test_reservoir]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DAQUA_APP_TEST_RESERVOIR

[env:test_reservoir_contact]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DAQUA_APP_TEST_RESERVOIR_CONTACT

[env:test_all_sensors]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DAQUA_APP_TEST_ALL_SENSORS
lib_deps =
  adafruit/Adafruit SHT31 Library

[env:test_dht11]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DAQUA_APP_TEST_DHT11
lib_deps =
  adafruit/DHT sensor library
