global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'aqua-atmos-backend'
    static_configs:
      - targets: ['dashboard:5000']
